# Generated by Django 5.0.1 on 2024-01-26 14:16

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_author_article_is_quote_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='SubArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/articles')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('header_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('footer_content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('is_quote', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubArticles', to='article.article')),
            ],
        ),
    ]
