# Generated by Django 5.0.1 on 2024-03-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_comment_parent_comment_top_level_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='article.tag'),
        ),
    ]
